image: node:latest

#stages: keywords em ordem de execução
stages:
  - install
  - validation #prettier, lint e jest
  - build
  - deploy

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

prettier:
  stage: validation
  dependencies:
    - install
  script:
    - npx prettier --write .

lint:
  stage: validation
  dependencies:
    - install
  script:
    - npm run lint

test:
  stage: validation
  dependencies:
    - install
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main' #corre apenas nesta branch
      when: on_success #apenas se for bem sucedido
      allow_failure: true
  artifacts:
    paths:
      - out/ #ainda não tenho a pasta, pq o build dá erro no comando

deploy:
  stage: deploy
  script:
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod #faz o deploy para o netlify
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main' #corre apenas nesta branch
      when: on_success #apenas se for bem sucedido
      allow_failure: true
