image: node:latest

stages:
  - install
  - validation #prettier, lint e jest
  - build
  - deploy

# Cache modules in between jobs
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

prettier:
  stage: validation
  dependencies:
    - install
  script:
    - npm run prettier #ou npx prettier --write .

lint:
  stage: validation
  dependencies:
    - install
  script:
    - npm run lint

jest:
  stage: validation
  dependencies:
    - install
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main' #corre apenas nesta branch
      when: on_success #apenas se os passos anteriores for bem sucedidos
      allow_failure: true
  artifacts:
    paths:
      - out/

deploy:
  stage: deploy
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
      when: on_success
      allow_failure: true
