# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 0 * * *"

jobs: 
  install:
    runs-on: -latest
    steps:
      - name: install
      - run: npm install
      
  prettier:
    runs-on: -latest
    needs: [install]
    steps:
      - name: prettier
      - run: |
           npm install
           npm run prettier
    
  lint:
    runs-on: -latest
    needs: [install]
    steps:
      - name: lint
      - run: |
           npm install
           npm run lint
    
  jest:
    runs-on: -latest
    needs: [install]
    steps:
      - name: test
      - run: |
           npm install
           npm test
